### ISSUE TITLE
[TYPO] Homepage typos

### ISSUE THREAD

**Issue by beralt85** [hongcoin/ico-website#15]
Hi guys,

I don't want to be pedantic, but I think the more professional the Homepage looks, the more people will start considering investing in HONG.

So I am listing some typos that I have found:
Top panel: Int**or**duction
Check balance popup: CH**CE**K MY BALANCE
"The required percentage for a valid voting result:" %-sign missing for freeze/kickoff

Cheers,
B

**Comment by cwlau** [comment]
Site is updated. Thank you for the findings!
